
/*
		BOOK OF MORMON
*/
var sm_bom = [
	{ 
		index: 1,
		reference: "1 Nephi 3:7",
		title: "I will go and do.",
		context: "The Lord commanded Nephi and his brothers to return to Jerusalem to get the brass plates.",
		principle: "The Lord prepares a way for us to keep His commandments.",
		application: "What has the Lord commanded you to do that some might consider to be difficult? How did He prepare a way for you to accomplish it?",
		verse: "And it came to pass that I, Nephi, said unto my father: I will go and do the things which the Lord hath commanded, for I know that the Lord giveth no commandments unto the children of men, save he shall prepare a way for them that they may accomplish the thing which he commandeth them.",
	},
	{
		index: 2,
		reference: "2 Nephi 2:25",
		title: "Adam fell that men might be.",
		context: "Lehi taught his sons about the necessity of the Fall and its consequences.",
		principle: "The Fall was a necessary part of Heavenly Father’s plan and allowed for our mortal existence.",
		application: "How does knowing about the Fall and mortality help you better understand your purpose in life?",
		verse: "Adam fell that men might be; and men are, that they might have joy.",
	},
	{
		index: 3,
		reference: "2 Nephi 2:27",
		title: "We are free to choose.",
		context: "Lehi taught his sons about the role of agency in the plan of salvation.",
		principle: "We are free to follow Jesus Christ, which leads to liberty and eternal life, or the devil, which leads to captivity and death.",
		application: "Think of a time you chose to obey a commandment. How do you feel that your obedience has or will lead to greater freedom?",
		verse: "Wherefore, men are free according to the flesh; and all things are given them which are expedient unto man. And they are free to choose liberty and eternal life, through the great Mediator of all men, or to choose captivity and death, according to the captivity and power of the devil; for he seeketh that all men might be miserable like unto himself.",
	},
	{
		index: 4,
		reference: "2 Nephi 9:28-29",
		title: "Learning is good if we follow God’s counsel.",
		context: "Jacob contrasted the greatness of Heavenly Father’s plan of salvation and the cunning plan of the devil.",
		principle: "The learned often take pride in their own wisdom and set aside the counsel of God. To obtain knowledge is good if we continue to obey God.",
		application: "How does obedience to the counsel of God help you keep a proper perspective concerning the wisdom of the world?",
		verse: "O that cunning plan of the evil one! O the vainness, and the frailties, and the foolishness of men! When they are learned they think they are wise, and they hearken not unto the counsel of God, for they set it aside, supposing they know of themselves, wherefore, their wisdom is foolishness and it profiteth them not. And they shall perish.  But to be learned is good if they hearken unto the counsels of God. ",
	},
	{
		index: 5,
		reference: "2 Nephi 25:23, 26",
		title: "By grace we are saved.",
		context: "Nephi explained some of the reasons why it is only through Jesus Christ that a person can be saved.",
		principle: "Through Jesus Christ, we can receive a remission of sins and be saved by grace after doing all we can do.",
		application: "What personal feelings and testimony would you share with a person who questioned whether Latter-day Saints believe in Jesus Christ?",
		verse: "For we labor diligently to write, to persuade our children, and also our brethren, to believe in Christ, and to be reconciled to God; for we know that it is by grace that we are saved, after all we can do.  And we talk of Christ, we rejoice in Christ, we preach of Christ, we prophesy of Christ, and we write according to our prophecies, that our children may know to what source they may look for a remission of their sins.",
	},
	{
		index: 6,
		reference: "2 Nephi 28:7-9",
		title: "We cannot justify any sin.",
		context: "The prophet Nephi taught his people of the great wickedness that would abound in the latter days.",
		principle: "In the last days, many will teach false, vain, and foolish doctrines.",
		application: "How can you recognize the foolish doctrines of the world?",
		verse: "Yea, and there shall be many which shall say: Eat, drink, and be merry, for tomorrow we die; and it shall be well with us.  And there shall also be many which shall say: Eat, drink, and be merry; nevertheless, fear God--he will justify in committing a little sin; yea, lie a little, take the advantage of one because of his words, dig a pit for thy neighbor; there is no harm in this; and do all these things, for tomorrow we die; and if it so be that we are guilty, God will beat us with a few stripes, and at last we shall be saved in the kingdom of God.  Yea, and there shall be many which shall teach after this manner, false and vain and foolish doctrines, and shall be puffed up in their hearts, and shall seek deep to hide their counsels from the Lord; and their works shall be in the dark.",
	},
	{
		index: 7,
		reference: "2 Nephi 31:19-20",
		title: "Endure to the end.",
		context: "Near the end of his ministry, Nephi wrote that all people must follow Jesus Christ’s example to inherit eternal life.",
		principle: "After we exercise faith, repent of our sins, are baptized, and receive the gift of the Holy Ghost, we must press forward in righteousness and endure to the end to receive eternal life.",
		application: "What counsel would you give a newly baptized member of the Church? What are you doing to “press forward with a steadfastness in Christ”?",
		verse: "And now, my beloved brethren, after ye have gotten into this strait and narrow path, I would ask if all is done? Behold, I say unto you, Nay; for ye have not come thus far save it were by the word of Christ with unshaken faith in him, relying wholly upon the merits of him who is mighty to save.  Wherefore, ye must press forward with a steadfastness in Christ, having a perfect brightness of hope, and a love of God and of all men. Wherefore, if ye shall press forward, feasting upon the word of Christ, and endure to the end, behold, thus saith the Father: Ye shall have eternal life. ",
	},
	{
		index: 8,
		reference: "2 Nephi 32:3",
		title: "Feast on the words of Christ.",
		context: "Near the end of his ministry, Nephi wrote what all people must do to understand and live the doctrine of Jesus Christ.",
		principle: "If we study the words of Christ and of His inspired servants, we will receive the direction we need to make correct choices.",
		application: "How have the words of Christ helped you know what to do? What will you do to “feast” on the words of Christ?",
		verse: "Angels speak by the power of the Holy Ghost; wherefore, they speak the words of Christ. Wherefore, I said unto you, feast upon the words of Christ; for behold, the words of Christ will tell you all things what ye should do. ",
	},
	{
		index: 9,
		reference: "2 Nephi 32:8-9",
		title: "Ye must pray always.",
		context: "Near the end of his ministry, Nephi wrote what all people must do to understand and live the doctrine of Jesus Christ.",
		principle: "The Spirit teaches us to pray.",
		application: "How can you remember to pray night and day? How can you seek the influence of the Holy Ghost in your prayers?",
		verse: "And now, my beloved brethren, I perceive that ye ponder still in your hearts; and it grieveth me that I must speak concerning this thing. For if ye would hearken unto the Spirit which teacheth a man to pray ye would know that ye must pray; for the evil spirit teacheth not a man to pray, but teacheth him that he must not pray.  But behold, I say unto you that ye must pray always, and not faint; that ye must not perform any thing unto the Lord save in the first place ye shall pray unto the Father in the name of Christ, that he will consecrate thy performance unto thee, that thy performance may be for the welfare of thy soul.",
	},
	{
		index: 10,
		reference: "Mosiah 2:17",
		title: "Serving others serves God.",
		context: "King Benjamin addressed his people, preparing them to take upon themselves the name of Jesus Christ.",
		principle: "When we serve our fellow beings, we serve God.",
		application: "What specific things can you do for those around you that the Savior would do if He were here?",
		verse: "And behold, I tell you these things that ye may learn wisdom; that ye may learn that when ye are in the service of your fellow beings ye are only in the service of your God.",
	},
	{
		index: 11,
		reference: "Mosiah 3:19",
		title: "Natural man is God’s enemy.",
		context: "King Benjamin addressed his people, preparing them to take upon themselves the name of Jesus Christ.",
		principle: "We overcome the natural man by yielding to the Holy Spirit and becoming a Saint through the Atonement of Jesus Christ.",
		application: "What does it mean to “yield to the enticings of the Holy Spirit”? What are some of the promptings the Holy Ghost has been giving you?",
		verse: "For the natural man is an enemy to God, and has been from the fall of Adam, and will be, forever and ever, unless he yields to the enticings of the Holy Spirit, and putteth off the natural man and becometh a saint through the atonement of Christ the Lord, and becometh as a child, submissive, meek, humble, patient, full of love, willing to submit to all things which the Lord seeth fit to inflict upon him, even as a child doth submit to his father. ",
	},
	{
		index: 12,
		reference: "Mosiah 4:30",
		title: "Watch your thoughts, words, and deeds.",
		context: "King Benjamin addressed his people, preparing them to take upon themselves the name of Jesus Christ.",
		principle: "We will be judged and held accountable for our thoughts, words, and deeds.",
		application: "What are some specific actions you have taken to maintain clean and virtuous thoughts, words, and actions throughout the day?",
		verse: "But this much I can tell you, that if ye do not watch yourselves, and your thoughts, and your words, and your deeds, and observe the commandments of God, and continue in the faith of what ye have heard concerning the coming of our Lord, even unto the end of your lives, ye must perish. And now, O man, remember, and perish not. ",
	},
	{
		index: 13,
		reference: "Alma 7:11-13",
		title: "Jesus Christ overcame sin and death.",
		context: "Alma prophesied to the people of Gideon that the Savior would come into the world and that they must prepare themselves.",
		principle: "Jesus Christ took upon himself the pains, sicknesses, and infirmities of His people; He delivered mankind from death and provided a way to overcome sin.",
		application: "When have you felt the healing power of the Atonement? Write in your journal or share with a friend your testimony of the Atonement’s healing power.",
		verse: "And he shall go forth, suffering pains and afflictions and temptations of every kind; and this that the word might be fulfilled which saith he will take upon him the pains and the sicknesses of his people.  And he will take upon him death, that he may loose the bands of death which bind his people; and he will take upon him their infirmities, that his bowels may be filled with mercy, according to the flesh, that he may know according to the flesh how to succor his people according to their infirmities.  Now the Spirit knoweth all things; nevertheless the Son of God suffereth according to the flesh that he might take upon him the sins of his people, that he might blot out their transgressions according to the power of his deliverance; and now behold, this is the testimony which is in me.",
	},
	{
		index: 14,
		reference: "Alma 32:21",
		title: "Faith is not a perfect knowledge.",
		context: "Alma taught the humble among the Zoramites regarding worship and faith.",
		principle: "Faith requires a person to believe things that are true but that may not be seen.",
		application: "How would you explain to a friend how something that cannot be seen can still be true?",
		verse: "And now as I said concerning faith--faith is not to have a perfect knowledge of things; therefore if ye have faith ye hope for things which are not seen, which are true. ",
	},
	{
		index: 15,
		reference: "Alma 37:35",
		title: "Learn in thy youth to keep the commandments.",
		context: "Alma counseled Helaman to prepare him for leadership responsibilities.",
		principle: "It is wise to learn in our youth to keep God’s commandments.",
		application: "What experiences have you had that have strengthened your desire to obey the commandments?",
		verse: "O, remember, my son, and learn wisdom in thy youth; yea, learn in thy youth to keep the commandments of God.",
	},
	{
		index: 16,
		reference: "Alma 39:9",
		title: "Go no more after the lust of your eyes.",
		context: "Alma corrected the behavior of Corianton, who had committed serious sins.",
		principle: "Those who give in to lust and immorality cannot be saved in the kingdom of God unless they repent.",
		application: "What do you do to overcome lustful thoughts and forsake your sins?",
		verse: "Now my son, I would that ye should repent and forsake your sins, and go no more after the lusts of your eyes, but cross yourself in all these things; for except ye do this ye can in nowise inherit the kingdom of God. Oh, remember, and take it upon you, and cross yourself in these things. ",
	},
	{
		index: 17,
		reference: "Alma 41:10",
		title: "Wickedness never was happiness.",
		context: "Alma taught his son Corianton about the eternal consequences of wickedness and righteousness.",
		principle: "Sin cannot bring lasting happiness.",
		application: "How has your happiness increased by following the example and teachings of Jesus Christ?",
		verse: "Do not suppose, because it has been spoken concerning restoration, that ye shall be restored from sin to happiness. Behold, I say unto you, wickedness never was happiness. ",
	},
	{
		index: 18,
		reference: "Helaman 5:12",
		title: "Build your foundation on Christ.",
		context: "Nephi and Lehi recalled the counsel of their father Helaman and devoted themselves to preaching to the wicked Nephites.",
		principle: "Only by basing our lives on Jesus Christ can we withstand Satan’s temptations.",
		application: "How has the gospel of Jesus Christ fortified you against temptations? How can you consistently base your choices on the life and teachings of the Savior?",
		verse: "And now, my sons, remember, remember that it is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your foundation; that when the devil shall send forth his mighty winds, yea, his shafts in the whirlwind, yea, when all his hail and his mighty storm shall beat upon you, it shall have no power over you to drag you down to the gulf of misery and endless wo, because of the rock upon which ye are built, which is a sure foundation, a foundation whereon if men build they cannot fall. ",
	},
	{
		index: 19,
		reference: "3 Nephi 12:48",
		title: "Ye should be perfect.",
		context: "Jesus Christ taught the Nephites the higher law and prepared them to be members of God’s kingdom.",
		principle: "We are commanded to be like Heavenly Father and Jesus Christ, who are perfect.",
		application: "What can you do right now to become more like Jesus Christ?",
		verse: "Therefore I would that ye should be perfect even as I, or your Father who is in heaven is perfect. ",
	},
	{
		index: 20,
		reference: "3 Nephi 18:15, 20-21",
		title: "Watch and pray always ",
		context: "Jesus taught the Nephites how to withstand the temptations of the devil.",
		principle: "Through prayer we can be given strength to resist temptation, receive our righteous desires, and be blessed in our families.",
		application: "What can you do to be more consistent in your personal and family prayers?",
		verse: "Verily, verily, I say unto you, ye must watch and pray always, lest ye be tempted by the devil, and ye be led away captive by him.  And whatsoever ye shall ask the Father in my name, which is right, believing that ye shall receive, behold it shall be given unto you.  Pray in your families unto the Father, always in my name, that your wives and your children may be blessed.",
	},
	{
		index: 21,
		reference: "Ether 12:6",
		title: "Witness comes after the trial of faith.",
		context: "Moroni included his own testimony, counsel, and understanding about faith while abridging the prophet Ether’s words.",
		principle: "The Lord blesses us with a spiritual confirmation after we have endured in faith.",
		application: "When have you demonstrated faith in Jesus Christ? What blessings did you receive?",
		verse: "And now, I, Moroni, would speak somewhat concerning these things; I would show unto the world that faith is things which are hoped for and not seen; wherefore, dispute not because ye see not, for ye receive no witness until after the trial of your faith. ",
	},
	{
		index: 22,
		reference: "Ether 12:27",
		title: "Weak things become strong.",
		context: "Moroni was concerned about the weakness of his writing. The Lord instructed him about overcoming weakness.",
		principle: "God gives us weakness to humble us. If we humble ourselves, our weakness can be made strong through faith in Jesus Christ.",
		application: "What weakness could you ask God to make strong? How can you humble yourself and have greater faith in Jesus Christ?",
		verse: "And if men come unto me I will show unto them their weakness. I give unto men weakness that they may be humble; and my grace is sufficient for all men that humble themselves before me; for if they humble themselves before me, and have faith in me, then will I make weak things become strong unto them. ",
	},
	{
		index: 23,
		reference: "Moroni 7:41",
		title: "Have hope through the Atonement of Christ.",
		context: "Mormon taught during a time of great wickedness how faith, hope, and charity help us become like Jesus Christ.",
		principle: "Our hope should be centered on Jesus Christ and His Atonement because of our faith in Him.",
		application: "How has your hope in the Atonement of Jesus Christ changed your outlook on the future? How can this hope influence the way you live?",
		verse: "And what is it that ye shall hope for? Behold I say unto you that ye shall have hope through the atonement of Christ and the power of his resurrection, to be raised unto life eternal, and this because of your faith in him according to the promise.",
	},
	{
		index: 24,
		reference: "Moroni 7:45, 47-48",
		title: "Charity suffereth long.",
		context: "Mormon taught during a time of great wickedness how faith, hope, and charity help us become like Jesus Christ.",
		principle: "We must have charity to be true followers of Jesus Christ. We should pray to the Father to be filled with this love.",
		application: "Consider the description of charity taught in Moroni 7, and ask your Heavenly Father how you can show that kind of love to family, friends, and others.",
		verse: "And charity suffereth long, and is kind, and envieth not, and is not puffed up, seeketh not her own, is not easily provoked, thinketh no evil, and rejoiceth not in iniquity but rejoiceth in the truth, beareth all things, believeth all things, hopeth all things, endureth all things.  But charity is the pure love of Christ, and it endureth forever; and whoso is found possessed of it at the last day, it shall be well with him.  Wherefore, my beloved brethren, pray unto the Father with all the energy of heart, that ye may be filled with this love, which he hath bestowed upon all who are true followers of his Son, Jesus Christ; that ye may become the sons of God; that when he shall appear we shall be like him, for we shall see him as he is; that we may have this hope; that we may be purified even as he is pure. Amen.",
	},
	{
		index: 25,
		reference: "Moroni 10:4-5",
		title: "The Holy Ghost reveals truth.",
		context: "Moroni closed his record with an invitation for all mankind to learn the truth of all things, including the Book of Mormon.",
		principle: "The Holy Ghost will reveal the truth of the Book of Mormon to those who ask God in faith with real intent.",
		application: "Explain to a friend how he or she can come to know the truthfulness of the Book of Mormon, and “the truth of all things.”",
		verse: "And when ye shall receive these things, I would exhort you that ye would ask God, the Eternal Father, in the name of Christ, if these things are not true; and if ye shall ask with a sincere heart, with real intent, having faith in Christ, he will manifest the truth of it unto you, by the power of the Holy Ghost.  And by the power of the Holy Ghost ye may know the truth of all things. ",
	}
];







/*
		NEW TESTAMENT
*/
var sm_nt = [
	{ 
		index: 1,
		reference: "Matthew 5:14-16",
		title: "Let your light so shine.",
		context: "In the Sermon on the Mount, Jesus Christ taught His disciples about how living the gospel affects others.",
		principle: "One’s example of living the gospel can encourage others to draw nearer to God.",
		application: "When has someone’s example inspired you to live the gospel? In what ways could you be an example to others?",
		verse: "Ye are the alight of the world. A city that is set on an hill cannot be hid.  Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house.  Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.",
	},
	{ 
		index: 2,
		reference: "Matthew 11:28–30",
		title: "Come unto me.",
		context: "As some people rejected Jesus, He offered promises to those who would accept Him.",
		principle: "If we come unto Jesus Christ, He will ease our burdens.",
		application: "When has the Lord helped you with a heavy burden? How can you draw nearer to Him? How could you use this verse to encourage a friend or family member who is feeling burdened?",
		verse: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.  Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.  For my yoke is easy, and my burden is light.",
	},
	{ 
		index: 3,
		reference: "Matthew 16:15-19",
		title: "The keys of the kingdom",
		context: "In Caesarea Philippi, Jesus Christ instructed His Apostles about what is necessary to lead the Church.",
		principle: "The Church of Jesus Christ is built upon revelation from God. Those who hold priesthood keys are authorized to govern the kingdom of God on the earth.",
		application: "What eternal truths have been revealed to you? In what ways have Church leaders with priesthood keys blessed your life? What should you do to show that you sustain Church leaders who hold priesthood keys?",
		verse: "He saith unto them, But whom say aye that I am?  And Simon Peter answered and said, Thou art the Christ, the Son of the living God.  And Jesus answered and said unto him, Blessed art thou, Simon Bar-jona: for flesh and blood hath not revealed it unto thee, but my Father which is in heaven.  And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it.  And I will give unto thee the keys of the kingdom of heaven: and whatsoever thou shalt bind on earth shall be bound in heaven: and whatsoever thou shalt loose on earth shall be loosed in heaven.",
	},
	{ 
		index: 4,
		reference: "Matthew 22:36–39",
		title: "Love the Lord; love thy neighbor.",
		context: "Jesus Christ responded to a Pharisee who asked which commandment was the greatest.",
		principle: "The two greatest commandments are to love God and to love our neighbor.",
		application: "How can you show love for God with your heart, soul, and mind? How can you show love to His children?",
		verse: "Master, which is the great commandment in the law?  Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.  This is the first and great commandment.  And the second is like unto it, Thou shalt love thy neighbour as thyself.",
	},
	{ 
		index: 5,
		reference: "Matthew 28:19-20",
		title: "Teach and baptize all nations.",
		context: "After His Resurrection, Jesus Christ gave instructions to His disciples.",
		principle: "As followers of Jesus Christ, we are to teach and baptize all nations.",
		application: "What could you do to help someone learn the gospel or keep his or her baptismal covenant?  What could you do to prepare to serve a mission?",
		verse: "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:  Teaching them to observe all things whatsoever I have ccommanded you: and, lo, I am with you alway, even unto the end of the world. Amen.",
	},
	{ 
		index: 6,
		reference: "Luke 24:36-39",
		title: "A resurrected body has flesh and bones.",
		context: "On the day of His Resurrection, Jesus Christ appeared to His disciples in Jerusalem and showed them His resur- rected body.",
		principle: "Jesus Christ is a resurrected being. A resurrected body is a body of flesh and bones.",
		application: "How is your testimony strengthened knowing that Jesus Christ was literally resurrected?",
		verse: "And as they thus spake, Jesus himself stood in the midst of them, and saith unto them, Peace be unto you.  But they were terrified and affrighted, and supposed that they had seen a spirit.  And he said unto them, Why are ye troubled? and why do thoughts arise in your hearts?  Behold my hands and my feet, that it is I myself: handle me, and see; for a spirit hath not flesh and bones, as ye see me have.",
	},
	{ 
		index: 7,
		reference: "John 3:5",
		title: "Born of water and of the Spirit",
		context: "A Pharisee named Nicodemus asked what Jesus Christ meant by being “born again.”",
		principle: "Baptism and receiving the Holy Ghost are necessary ordinances for spiritual rebirth and entering the celestial kingdom.",
		application: "How has your baptism and receiving the gift of the Holy Ghost made a difference in your life? What can you do to keep your baptismal covenant and seek the companionship of the Holy Ghost?",
		verse: "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
	},
	{ 
		index: 8,
		reference: "John 14:6",
		title: "The way, the truth, and the life",
		context: "During the Last Supper, Jesus Christ answered Thomas’s question about how the disciples could know the way to the Father.",
		principle: "The only way to receive eternal life and dwell with Father in Heaven is through Jesus Christ.",
		application: "What are you doing to rely upon Jesus Christ as you strive to come unto the Father?",
		verse: "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.",
	},
	{ 
		index: 9,
		reference: "John 14:15",
		title: "If ye love me, keep my commandments.",
		context: "During the Last Supper, Jesus Christ taught His disciples how they could show their love for Him.",
		principle: "We manifest our love for the Lord by keeping His commandments.",
		application: "Set a goal in an area in your life where you could show greater love for the Lord through increased obedience.",
		verse: "If ye love me, keep my commandments.",
	},
	{ 
		index: 10,
		reference: "John 17:3",
		title: "Knowing God and Jesus Christ is eternal life.",
		context: "The night before His Crucifixion, Jesus Christ prayed for His followers.",
		principle: "As we come to truly know Heavenly Father and Jesus Christ, we can obtain eternal life.",
		application: "What can you do to better know Heavenly Father and Jesus Christ? What can you do to strengthen your relationship with Them?",
		verse: "And this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent.",
	},
	{ 
		index: 11,
		reference: "Acts 2:36-38",
		title: "Repent, be baptized, and receive the Holy Ghost.",
		context: "Fifty days after the Savior’s Resurrection, the Apostle Peter taught a multitude in Jerusalem what they must do to be saved.",
		principle: "Repentance and baptism for the remission of sins prepare us to receive the gift of the Holy Ghost.",
		application: "How could you use this scripture to help a friend understand what each of us must do to be forgiven of our sins and receive the Holy Ghost?",
		verse: "Therefore let all the house of Israel know assuredly, that God hath made that same Jesus, whom ye have crucified, both Lord and Christ.  Now when they heard this, they were pricked in their heart, and said unto Peter and to the rest of the apostles, Men and brethren, what shall we do?  Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.",
	},
	{ 
		index: 12,
		reference: "Acts 3:19–21",
		title: "The times of restitution",
		context: "The Apostle Peter testified to a multi- tude in Jerusalem concerning our day.",
		principle: "Prophets in all ages have foretold the latter-day restitution (restoration) of all things.",
		application: "What additional scriptures show that the Lord would restore the gospel before His Second Coming?",
		verse: "Repent ye therefore, and be converted, that your sins may be blotted out, when the times of refreshing shall come from the presence of the Lord;  And he shall send Jesus Christ, which before was preached unto you:  Whom the heaven must receive until the times of restitution of all things, which God hath spoken by the mouth of all his holy prophets since the world began.",
	},
	{ 
		index: 13,
		reference: "1 Corinthians 6:19-20",
		title: "Your body is a temple.",
		context: "In a letter to members of the Church in Corinth, the Apostle Paul taught the Saints why sexual sins were so serious.",
		principle: "Our bodies are sacred like temples and should be clean and holy.",
		application: "How does the doctrine in this scripture help answer questions about modesty? Chastity? Tattoos and piercings? The Word of Wisdom?",
		verse: "What? know ye not that your body is the temple of the Holy Ghost which is in you, which ye have of God, and ye are not your own?  For ye are bought with a price: therefore glorify God in your body, and in your spirit, which are God’s.",
	},
	{ 
		index: 14,
		reference: "1 Corinthians 15:20-22",
		title: "In Christ shall all be resurrected.",
		context: "When some Saints in Corinth taught that there is no resurrection of the dead, the Apostle Paul wrote to correct them.",
		principle: "Because Jesus Christ overcame death and was resurrected, all mankind will also be resurrected.",
		application: "Share your testimony of the Resurrection of Jesus Christ with someone. How does this doctrine provide comfort to someone who has lost a loved one?",
		verse: "But now is Christ risen from the dead, and become the firstfruits of them that slept.  For since by man came death, by man came also the resurrection of the dead.  For as in Adam all die, even so in Christ shall all be made alive.",
	},
	{ 
		index: 15,
		reference: "1 Corinthians 15:40-42",
		title: "Degrees of glory",
		context: "In a letter to members of the Church in Corinth, the Apostle Paul answered questions about how the dead will be raised and what kind of body they will be resurrected with.",
		principle: "Resurrected bodies differ in glory just as the sun, moon, and stars differ in their brightness.",
		application: "Read Doctrine and Covenants 76:50–70. What must you do to inherit a resurrected body of celestial glory?",
		verse: "There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another.  There is one glory of the sun, and another glory of the moon, and another glory of the stars: for one star differeth from another star in glory.  So also is the resurrection of the dead. It is sown in corruption; it is raised in incorruption:",
	},
	{ 
		index: 16,
		reference: "Galatians 5:22–23",
		title: "Fruit of the Spirit",
		context: "In a letter to the Saints in Galatia, the Apostle Paul taught about the qualities that the Spirit instills in those who seek to “walk in the Spirit.”",
		principle: "Having the Holy Ghost often results in feelings of love, joy, peace, longsuf- fering, gentleness, goodness, faith, meekness, and temperance.",
		application: "When have you experienced the fruits of the Spirit? What can you do to invite the companionship of the Holy Ghost and enjoy these fruits of the Spirit in your life?",
		verse: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith,  Meekness, temperance: against such there is no law.",
	},
	{ 
		index: 17,
		reference: "Ephesians 4:11-14",
		title: "Apostles and prophets help perfect the Saints.",
		context: "In an epistle to the Saints in Ephesus, the Apostle Paul taught about the organization and purpose of the Church.",
		principle: "The Church organization is given by God for perfecting and edifying the Saints and accomplishing the work of the ministry.",
		application: "In what ways do Church leaders keep us from being “carried about with every wind of doctrine”?  How can you best show appreciation for a local Church leader?",
		verse: "And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers;  For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ:  Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:  That we henceforth be no more children, tossed to and fro, and carried about with every wind of doctrine, by the sleight of men, and cunning craftiness, whereby they lie in wait to deceive;",
	},
	{
		index: 18,
		reference: "Philippians 4:13",
		title: "I can do all things through Christ.",
		context: "While imprisoned, the Apostle Paul wrote to encourage the Saints in Philippi.",
		principle: "Jesus Christ can strengthen us to do whatever God requires of us.",
		application: "Write in your journal about a time when the Lord gave you strength to meet a challenge.",
		verse: "I can do all things through Christ which strengtheneth me."
	}
	{ 
		index: 19,
		reference: "2 Thessalonians 2:1-3",
		title: "Apostasy foretold",
		context: "Some of the Saints in Thessalonica believed the Second Coming of Jesus Christ would soon occur. In his letter to them, the Apostle Paul corrected this misunderstanding.",
		principle: "It was foretold that a period of apostasy would precede the Second Coming of Jesus Christ.",
		application: "How would you answer a friend who asked, “Hasn’t Christ’s Church been on the earth since He established it? Why would there need to be a Restoration?”",
		verse: "Now we beseech you, brethren, by the coming of our Lord Jesus Christ, and by our gathering together unto him, That ye be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand.  Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition;",
	},
	{ 
		index: 20,
		reference: "2 Timothy 3:15-17",
		title: "Scripture given for doctrine, reproof, and correction",
		context: "The Apostle Paul wrote to Timothy and encouraged him as he faced challenges among Church members.",
		principle: "The inspired doctrine, reproof, and correction found in scripture will help lead us to salvation.",
		application: "When has scripture study helped you understand doctrine, feel reproof, or receive correction?",
		verse: "And that from a child thou hast known the holy scriptures, which are able to make thee wise unto salvation through faith which is in Christ Jesus.  All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness:  That the man of God may be perfect, throughly furnished unto all good works.",
	},
	{ 
		index: 21,
		reference: "Hebrews 12:9",
		title: "God is the Father of our spirits.",
		context: "The Apostle Paul encouraged members of the Church to be faithful to their Heavenly Father.",
		principle: "God is the Father of our spirits, and we should be obedient to Him.",
		application: "How does your knowledge that God is the Father of your spirit influence how you view the commandments?",
		verse: "Furthermore we have had fathers of our flesh which corrected us, and we gave them reverence: shall we not much rather be in subjection unto the Father of spirits, and live?",
	},
	{ 
		index: 22,
		reference: "James 1:5-6",
		title: "If you lack wisdom, ask God.",
		context: "James wrote to Church members about how to obtain divine guidance.",
		principle: "God willingly gives wisdom to those who ask of Him in faith.",
		application: "When has God given you guidance in answer to your prayers? What can you do to pray with greater faith?",
		verse: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.  But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.",
	},
	{ 
		index: 23,
		reference: "James 2:17-18",
		title: "Faith without works is dead.",
		context: "James wrote to Church members in response to some who claimed that works were not needed to express their faith.",
		principle: "Faith without works is dead.",
		application: "When have you seen faith manifested in the works of someone you know? What specific things could you do this week that would show you have faith in Jesus Christ?",
		verse: "Even so faith, if it hath not works, is dead, being alone.  Yea, a man may say, Thou hast faith, and I have works: shew me thy faith without thy works, and I will shew thee my faith by my works.  Revelation 14:6-7And I saw another angel fly in the midst of heaven, having the everlasting gospel to preach unto them that dwell on the earth, and to every nation, and kindred, and tongue, and people,  Saying with a loud voice, Fear God, and give glory to him; for the hour of his judgment is come: and worship him that made heaven, and earth, and the sea, and the fountains of waters.",
	},
	{
		index: 24,
		refernce: "1 Peter 4:6",
		title: "The gospel is preached to the dead.",
		context: "When the Saints in Asia Minor were going through many trials, the Apostle Peter wrote and assured them that Jesus Christ was the Savior and judge of the living and the dead.",
		principle: "The gospel is preached to those who have died so they may have the same opportunity as those who heard the gospel message in mortality.",
		application: "Seek opportunities to do family history research about your ancestors and to participate in temple ordinances in their behalf.",
		verse: ""
	},
	{ 
		index: 25,
		reference: "Revelation 20:12",
		title: "Judged before God",
		context: "While on the Isle of Patmos, the Apostle John saw a vision of all the dead being brought before God to be judged.",
		principle: "Everyone will be judged by God according to their works out of the books that have been written.",
		application: "How does knowing you will be judged according to your works affect the decisions you will make today?",
		verse: "And I saw the dead, small and great, stand before God; and the books were opened: and another book was opened, which is the book of life: and the dead were judged out of those things which were written in the books, according to their works."
	}
];








/*
		OLD TESTAMENT
*/
var sm_ot = [
	{ 
		index: 1,
		reference: "Moses 1:39",
		title: "This is God’s work and glory.",
		context: "While on a high mountain, God spoke with Moses face-to-face and explained His eternal purpose for mankind.",
		principle: "Heavenly Father’s plan provides a way for us to live forever and become like Him.",
		application: "How can you assist God in His work? How can you help others seek eternal life?",
		verse: "For behold, this is my work and my glory—to bring to pass the immortality and eternal life of man.",
	},
	{ 
		index: 2,
		reference: "Moses 7:18",
		title: "Zion—one heart and one mind in righteousness",
		context: "Enoch taught the gospel and estab- lished a city of righteousness during a time of great wickedness.",
		principle: "The Lord’s people are united, live righteously, and care for one another.",
		application: "What can you do to build unity, promote righteousness, and assist those in need in your family, ward, or branch?",
		verse: "And the Lord called his people Zion, because they were of one heart and one mind, and dwelt in righteousness; and there was no poor among them.",
	},
	{ 
		index: 3,
		reference: "Abraham 3:22–23",
		title: "Abraham was chosen before he was born.",
		context: "God taught Abraham about premortal spirits.",
		principle: "We lived with God before birth, and He chose His noble and great children to become rulers and leaders here upon the earth.",
		application: "How does the truth that God knew you before you were born inspire you to follow Him during mortality?",
		verse: "Now the Lord had shown unto me, Abraham, the intelligences that were organized before the world was; and among all these there were many of the noble and great ones;  And God saw these souls that they were good, and he stood in the midst of them, and he said: These I will make my rulers; for he stood among those that were spirits, and he saw that they were good; and he said unto me: Abraham, thou art one of them; thou wast chosen before thou wast born.",
	},
	{ 
		index: 4,
		reference: "Genesis 1:26–27",
		title: "God created man in His own image.",
		context: "The Creation account sets forth the placing of Adam and Eve on the earth.",
		principle: "Men and women are created in God’s image and given dominion over all animals and creatures on the earth.",
		application: "You are a child of God, made in His image. When you pray to Heavenly Father, remember that He is a loving Father.",
		verse: "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth.  So God created man in his own image, in the image of God created he him; male and female created he them.",
	},
	{ 
		index: 5,
		reference: "Genesis 2:24",
		title: "Husbands and wives should be one.",
		context: "Following the creation of Eve, God taught Adam and Eve that unity should exist in their marriage.",
		principle: "Marriage between a man and a woman is ordained of God.",
		application: "What will you do now to prepare for marriage in the future? What standards will you follow to honor the union with your future spouse?",
		verse: "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh.",
	},
	{ 
		index: 6,
		reference: "Genesis 39:9",
		title: "Joseph resisted temptation.",
		context: "Joseph was repeatedly approached by Potiphar’s wife to commit adultery.",
		principle: "Sexual immorality is a sin against God.",
		application: "Identify specific standards in the For the Strength of Youth pamphlet that can help you stay morally pure.",
		verse: "There is none greater in this house than I; neither hath he kept back any thing from me but thee, because thou art his wife: how then can I do this great wickedness, and sin against God?",
	},
	{ 
		index: 7,
		reference: "Exodus 19:5–6",
		title: "Ye shall be a holy nation.",
		context: "At Mount Sinai, the Lord invited the children of Israel to become His cov- enant people.",
		principle: "If we obey the Lord’s voice and keep His covenants, then we will become His holy people.",
		application: "What will you do to better keep the covenants you have made with the Lord?",
		verse: "Now therefore, if ye will obey my voice indeed, and keep my covenant, then ye shall be a peculiar treasure unto me above all people: for all the earth is mine:  And ye shall be unto me a kingdom of priests, and an holy nation. These are the words which thou shalt speak unto the children of Israel.",
	},
	{ 
		index: 8,
		reference: "Exodus 20:3–17",
		title: "The Ten Commandments",
		context: "Near Mount Sinai, the Lord gave the children of Israel commandments through His servant Moses.",
		principle: "As we keep the Ten Commandments, we live in harmony with God and man.",
		application: "Consider each of the Ten Commandments and how well you are following it. Commit to obey them more fully.",
		verse: "Thou shalt have no other gods before me.  Thou shalt not make unto thee any graven image, or any likeness of any thing that is in heaven above, or that is in the earth beneath, or that is in the water under the earth:  Thou shalt not bow down thyself to them, nor serve them: for I the Lord thy God am a jealous God, visiting the iniquity of the fathers upon the children unto the third and fourth generation of them that hate me;  And shewing mercy unto thousands of them that love me, and keep my commandments.  Thou shalt not take the name of the Lord thy God in vain; for the Lord will not hold him guiltless that taketh his name in vain.  Remember the sabbath day, to keep it holy.  Six days shalt thou labour, and do all thy work:  But the seventh day is the sabbath of the Lord thy God: in it thou shalt not do any work, thou, nor thy son, nor thy daughter, thy manservant, nor thy maidservant, nor thy cattle, nor thy stranger that is within thy gates:  For in six days the Lord made heaven and earth, the sea, and all that in them is, and rested the seventh day: wherefore the Lord blessed the sabbath day, and hallowed it.  Honour thy father and thy mother: that thy days may be long upon the land which the Lord thy God giveth thee.  Thou shalt not kill.  Thou shalt not commit adultery.  Thou shalt not steal.  Thou shalt not bear false witness against thy neighbour.  Thou shalt not covet thy neighbour's house, thou shalt not covet thy neighbour's wife, nor his manservant, nor his maidservant, nor his ox, nor his ass, nor any thing that is thy neighbour's.",
	},
	{ 
		index: 9,
		reference: "Joshua 24:15",
		title: "Choose to serve the Lord.",
		context: "Joshua taught the children of Israel what the Lord had done to preserve them. He encouraged them to serve the Lord.",
		principle: "We can choose whether or not we will serve the Lord and follow Him.",
		application: "What actions in your life demonstrate your choice to serve the Lord?",
		verse: "And if it seem evil unto you to serve the Lord, choose you this day whom ye will serve; whether the gods which your fathers served that were on the other side of the flood, or the gods of the Amorites, in whose land ye dwell: but as for me and my house, we will serve the Lord.",
	},
	{ 
		index: 10,
		reference: "1 Samuel 16:7",
		title: "The Lord looks on the heart.",
		context: "Samuel assumed that Eliab, the eldest son of Jesse, was the one the Lord had selected to be Israel’s new king because of his strong physical appearance.",
		principle: "God judges us by our thoughts and desires rather than by our outward appearance.",
		application: "Rather than focus on outward appear- ance, pray to see yourself and others as God sees you.",
		verse: "But the Lord said unto Samuel, Look not on his countenance, or on the height of his stature; because I have refused him: for the Lord seeth not as man seeth; for man looketh on the outward appearance, but the Lord looketh on the heart.",
	},
	{ 
		index: 11,
		reference: "Psalm 24:3–4",
		title: "Clean hands, pure heart",
		context: "In a psalm (song) of praise to God, the psalmist asked who would be worthy to stand in holy places such as temples.",
		principle: "If we repent and live pure lives, then we are worthy to receive temple ordi- nances and enter the celestial kingdom.",
		application: "What can you do to be clean and pure as you interact with media and tech- nology? If you are able, make plans to attend the temple regularly.",
		verse: "Who shall ascend into the hill of the Lord? or who shall stand in his holy place?  He that hath clean hands, and a pure heart; who hath not lifted up his soul unto vanity, nor sworn deceitfully.",
	},
	{ 
		index: 12,
		reference: "Psalm 119:105",
		title: "God’s word is a lamp unto my feet.",
		context: "In a psalm (song) about God’s law, the psalmist compared God’s word to a light that guides us on the path of life.",
		principle: "The word of God gives direction for our lives.",
		application: "Seek answers to your questions and guidance for your life as you study the scriptures and the words of living prophets.",
		verse: "Thy word is a lamp unto my feet, and a light unto my path.",
	},
	{ 
		index: 13,
		reference: "Psalm 127:3",
		title: "Children are an heritage of the Lord.",
		context: "A psalm (song) about God’s blessings teaches that children are a precious gift from God.",
		principle: "Children are to be cherished as gifts from God.",
		application: "In what ways are you preparing your- self now for the sacred responsibility of raising and caring for your own children?",
		verse: "Lo, children are an heritage of the Lord: and the fruit of the womb is his reward.",
	},
	{ 
		index: 14,
		reference: "Proverbs 3:5–6",
		title: "Trust in the Lord.",
		context: "The book of Proverbs contains gospel principles, poems, and parables that encourage righteous living.",
		principle: "If we place our complete trust in God, He will guide us in our lives.",
		application: "How can you rely more on the Lord and less on your own understanding? As you learn to increase your trust in the Lord, how will your life have more divine direction and purpose?",
		verse: "Trust in the Lord with all thine heart; and lean not unto thine own understanding.  In all thy ways acknowledge him, and he shall direct thy paths.",
	},
	{ 
		index: 15,
		reference: "Isaiah 1:18",
		title: "Though your sins be as scarlet",
		context: "Through the prophet Isaiah, the Lord encouraged His children to repent and become clean.",
		principle: "When we repent, the blood of Jesus Christ cleanses us from our sins and we can be completely forgiven.",
		application: "If you have unresolved sin, exercise your faith to move forward in the repentance process.",
		verse: "Come now, and let us reason together, saith the Lord: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.",
	},
	{ 
		index: 16,
		reference: "Isaiah 5:20",
		title: "Woe unto them that call evil good.",
		context: "Isaiah warned the children of Israel of the sorrow and suffering that would come upon them because of their unrighteousness.",
		principle: "Unhappiness results when people pro- mote evil as good and call good evil.",
		application: "When have you seen the media portray evil as good and good as evil? How can you avoid being deceived by the false philosophies of the world?",
		verse: "Woe unto them that call evil good, and good evil; that put darkness for light, and light for darkness; that put bitter for sweet, and sweet for bitter!",
	},
	{ 
		index: 17,
		reference: "Isaiah 29:13–14",
		title: "A marvelous work and a wonder",
		context: "Isaiah prophesied that the Lord would restore the gospel in the latter days, following a time of apostasy.",
		principle: "The Restoration of the gospel is a marvelous work that corrects false doctrines and counters the wisdom of the world.",
		application: "How has the restored gospel helped you draw nearer to the Lord?",
		verse: "Wherefore the Lord said, Forasmuch as this people draw near me with their mouth, and with their lips do honour me, but have removed their heart far from me, and their fear toward me is taught by the precept of men:  Therefore, behold, I will proceed to do a marvellous work among this people, even a marvellous work and a wonder: for the wisdom of their wise men shall perish, and the understanding of their prudent men shall be hid.",
	},
	{ 
		index: 18,
		reference: "Isaiah 53:3–5",
		title: "Jesus Christ bore our griefs and suf- fered for our sins.",
		context: "Isaiah prophesied of the life and aton- ing mission of Jesus Christ approxi- mately 700 years before His birth.",
		principle: "Jesus Christ suffered for our sins and sorrows; we can be forgiven and healed through the Atonement.",
		application: "When have you felt the healing power of the Atonement? Write in your journal or share with someone your feelings for Jesus Christ and His Atonement.",
		verse: "He is despised and rejected of men; a man of sorrows, and acquainted with grief: and we hid as it were our faces from him; he was despised, and we esteemed him not.  Surely he hath borne our griefs, and carried our sorrows: yet we did esteem him stricken, smitten of God, and afflicted.  But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
	},
	{ 
		index: 19,
		reference: "Isaiah 58:6–7",
		title: "The law of the fast",
		context: "After the prophet Isaiah identified ways the people were failing to live the law of the fast, he taught them about the true purposes and blessings of fasting.",
		principle: "Fasting helps relieve the burdens of ourselves and others and helps us care for the poor.",
		application: "When have you received blessings from a fast? When fasting, plan to fast with a specific purpose.",
		verse: "Is not this the fast that I have chosen? to loose the bands of wickedness, to undo the heavy burdens, and to let the oppressed go free, and that ye break every yoke?  Is it not to deal thy bread to the hungry, and that thou bring the poor that are cast out to thy house? when thou seest the naked, that thou cover him; and that thou hide not thyself from thine own flesh?",
	},
	{ 
		index: 20,
		reference: "Isaiah 58:13–14",
		title: "The Sabbath is the Lord’s holy day.",
		context: "The prophet Isaiah instructed the peo- ple to keep the Sabbath day holy and taught about the blessings that come from Sabbath-day observance.",
		principle: "If we honor God by seeking to do His will on the Sabbath day, then we will prosper.",
		application: "Evaluate your Sabbath-day observance and determine whether your Sabbath- day activities honor God. Strive to better serve and honor God on His holy day.",
		verse: "If thou turn away thy foot from the sabbath, from doing thy pleasure on my holy day; and call the sabbath a delight, the holy of the Lord, honourable; and shalt honour him, not doing thine own ways, nor finding thine own pleasure, nor speaking thine own words:  Then shalt thou delight thyself in the Lord; and I will cause thee to ride upon the high places of the earth, and feed thee with the heritage of Jacob thy father: for the mouth of the Lord hath spoken it.",
	},
	{ 
		index: 21,
		reference: "Jeremiah 1:4–5",
		title: "Jeremiah was foreordained before birth.",
		context: "As the Lord called Jeremiah to proph- esy to the people of Judah, He revealed that Jeremiah had been ordained to be a prophet before he was born.",
		principle: "God knew us before we were born and foreordained us for earthly missions.",
		application: "Examine your patriarchal blessing to gain insights into your purposes on earth. If you have not yet received a patriarchal blessing, prepare to receive one.",
		verse: "Then the word of the Lord came unto me, saying,  Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee, and I ordained thee a prophet unto the nations.",
	},
	{ 
		index: 22,
		reference: "Ezekiel 37:15–17",
		title: "The Bible and the Book of Mormon are joined together.",
		context: "Ezekiel prophesied that as part of the gathering of Israel in the last days, the Bible and the Book of Mormon would be joined together.",
		principle: "The Bible and the Book of Mormon have come together to witness of Jesus Christ in our day.",
		application: "As you study the scriptures, look for truths that are supported in both the Bible and the Book of Mormon.",
		verse: "The word of the Lord came again unto me, saying,  Moreover, thou son of man, take thee one stick, and write upon it, For Judah, and for the children of Israel his companions: then take another stick, and write upon it, For Joseph, the stick of Ephraim, and for all the house of Israel his companions:  And join them one to another into one stick; and they shall become one in thine hand.",
	},
	{ 
		index: 23,
		reference: "Amos 3:7",
		title: "God reveals His secret to His prophets.",
		context: "As the prophet Amos warned of com- ing judgments of the Lord, he testified that God reveals knowledge to His prophets.",
		principle: "The Lord reveals His will through prophets.",
		application: "How have you come to know that God speaks through prophets today? What are the current prophets counseling you to do?",
		verse: "Surely the Lord God will do nothing, but he revealeth his secret unto his servants the prophets.",
	},
	{ 
		index: 24,
		reference: "Malachi 3:8–10",
		title: "Paying tithing brings blessings.",
		context: "Through the prophet Malachi, the Lord taught wayward Israel to return to Him by living the law of tithing.",
		principle: "If we pay tithes and offerings, then God will open the windows of heaven and pour out blessings upon us.",
		application: "What blessings have you received as a result of obeying the law of tithing?",
		verse: "Will a man rob God? Yet ye have robbed me. But ye say, Wherein have we robbed thee? In tithes and offerings.  Ye are acursed with a curse: for ye have robbed me, even this whole nation.",
	},
	{ 
		index: 25,
		reference: "Malachi 4:5–6",
		title: "Elijah will turn the hearts of fathers and children.",
		context: "Malachi prophesied that before the Second Coming of Jesus Christ, the prophet Elijah would restore the authority to perform ordinance work for the dead.",
		principle: "Because Elijah came and restored priesthood keys, we can perform ordinance work for our kindred dead.",
		application: "Learn how to use the family history tools that the church provides. Prepare the name of at least one of your ancestors for temple ordinances.",
		verse: "Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the Lord:  And he shall turn the heart of the fathers to the children, and the heart of the children to their fathers, lest I come and smite the earth with a curse.",
	}
];
